### ISSUE TITLE
Command line tool: insufficient info as output

### ISSUE THREAD

**Issue by ok11** [mulesoft/raml-for-jax-rs#103]
Hi guys,

How can I get a reasonable description of an error (including line, position in the RAML file)?
The following output does not really help to come to the root cause:

C:\workspace\services\service-sample>java -cp c:\workspace\hcp-services\tools\raml-to-jax-rs.jar org.raml.jaxrs.codegen.core.Launcher -basePackageName org.example -outputDirectory target/generated-sources
-sourceDirectory src/main/resources/api
log4j:WARN No appenders could be found for logger (org.raml.parser.loader.FileResourceLoader).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
java.lang.ClassCastException: org.yaml.snakeyaml.nodes.ScalarNode cannot be cast to org.yaml.snakeyaml.nodes.MappingNode
        at org.raml.parser.visitor.TemplateResolver.loopTemplateSequence(TemplateResolver.java:145)
        at org.raml.parser.visitor.TemplateResolver.init(TemplateResolver.java:129)
        at org.raml.parser.visitor.RamlValidationService.preValidation(RamlValidationService.java:51)
        at org.raml.parser.visitor.YamlValidationService.validate(YamlValidationService.java:64)
        at org.raml.parser.visitor.YamlValidationService.validate(YamlValidationService.java:95)
        at org.raml.parser.visitor.YamlValidationService.validate(YamlValidationService.java:77)
        at org.raml.jaxrs.codegen.core.Generator.run(Generator.java:124)
        at org.raml.jaxrs.codegen.core.Launcher.main(Launcher.java:63)
java.lang.IllegalArgumentException: Invalid RAML definition:
-1 Invalid RAML
        at org.raml.jaxrs.codegen.core.Generator.run(Generator.java:142)
        at org.raml.jaxrs.codegen.core.Launcher.main(Launcher.java:63)

**Comment by KonstantinSviridov** [comment]
Hi, @ok11 

Your exception is thrown by the RAML Java parser which is not controlled by the raml-for-jax-rs team. Thus, your request should be posted [here](https://github.com/raml-org/raml-java-parser/issues).

If you whish, I can create an issue for you and take participation in discussion, if needed.

Regards, Konstantin.

**Comment by ok11** [comment]
Hi Konstantin,

thanks a lot, I would appreciate much, if you mediate that.

**Comment by KonstantinSviridov** [comment]
I've created an issue
https://github.com/raml-org/raml-java-parser/issues/66

Please, provide the parser team with details once they ask for.
