### ISSUE TITLE
execution failed jlibs:jlibs-xml:jar:1.0 dependency not resolved

### ISSUE THREAD

**Issue by McFoggy** [mulesoft/raml-for-jax-rs#110]
testing the plugin on a pure jee7 war project with jaxrs using following configuration:
```xml
<plugin>
    <groupId>org.raml.plugins</groupId>
    <artifactId>jaxrs-raml-maven-plugin</artifactId>
    <version>1.3.3</version>
    <executions>
        <execution>
            <goals>
                <goal>generate-raml</goal>
            </goals>
            <phase>process-classes</phase>
        </execution>
    </executions>
</plugin>
```

`mvn package` from command line is failing during plugin execution with the following error (non resolved jlibs dependency from an eclipse p2 repository)

```
[ERROR] Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml (default) on project clinicalproblems-war: Execution default of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml failed: Plugin org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3 or one of its dependencies could not be resolved: Failed to collect dependencies at org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.3 -> org.raml:com.mulesoft.jaxrs.raml.generator:jar:1.3.3 -> jlibs:jlibs-xml:jar:1.0: Failed to read artifact descriptor for jlibs:jlibs-xml:jar:1.0: Could not transfer artifact jlibs:jlibs-xml:pom:1.0 from/to kepler (http://download.eclipse.org/releases/kepler): Cannot access http://download.eclipse.org/releases/kepler with type p2 using the available connector factories: BasicRepositoryConnectorFactory: Cannot access http://download.eclipse.org/releases/kepler with type p2 using the available layout factories: Maven2RepositoryLayoutFactory: Unsupported repository layout p2 -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml (default) on project clinicalproblems-war: Execution default of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml failed: Plugin org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3 or one of its dependencies could not be resolved: Failed to collect dependencies at org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.3 -> org.raml:com.mulesoft.jaxrs.raml.generator:jar:1.3.3 -> jlibs:jlibs-xml:jar:1.0
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:224)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:120)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:355)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:216)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:160)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default of goal org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3:generate-raml failed: Plugin org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3 or one of its dependencies could not be resolved: Failed to collect dependencies at org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.3 -> org.raml:com.mulesoft.jaxrs.raml.generator:jar:1.3.3 -> jlibs:jlibs-xml:jar:1.0
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:104)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
        ... 19 more
Caused by: org.apache.maven.plugin.PluginResolutionException: Plugin org.raml.plugins:jaxrs-raml-maven-plugin:1.3.3 or one of its dependencies could not be resolved: Failed to collect dependencies at org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.3 -> org.raml:com.mulesoft.jaxrs.raml.generator:jar:1.3.3 -> jlibs:jlibs-xml:jar:1.0
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:204)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.createPluginRealm(DefaultMavenPluginManager.java:361)
        at org.apache.maven.plugin.internal.DefaultMavenPluginManager.setupPluginRealm(DefaultMavenPluginManager.java:329)
        at org.apache.maven.plugin.DefaultBuildPluginManager.getPluginRealm(DefaultBuildPluginManager.java:229)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:100)
        ... 20 more
Caused by: org.eclipse.aether.collection.DependencyCollectionException: Failed to collect dependencies at org.raml.plugins:jaxrs-raml-maven-plugin:jar:1.3.3 -> org.raml:com.mulesoft.jaxrs.raml.generator:jar:1.3.3 -> jlibs:jlibs-xml:jar:1.0
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:291)
        at org.eclipse.aether.internal.impl.DefaultRepositorySystem.collectDependencies(DefaultRepositorySystem.java:316)
        at org.apache.maven.plugin.internal.DefaultPluginDependenciesResolver.resolve(DefaultPluginDependenciesResolver.java:192)
        ... 24 more
Caused by: org.eclipse.aether.resolution.ArtifactDescriptorException: Failed to read artifact descriptor for jlibs:jlibs-xml:jar:1.0
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:302)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.readArtifactDescriptor(DefaultArtifactDescriptorReader.java:217)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.resolveCachedArtifactDescriptor(DefaultDependencyCollector.java:525)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.getArtifactDescriptorResult(DefaultDependencyCollector.java:509)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:409)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.doRecurse(DefaultDependencyCollector.java:494)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:458)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.processDependency(DefaultDependencyCollector.java:363)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.process(DefaultDependencyCollector.java:351)
        at org.eclipse.aether.internal.impl.DefaultDependencyCollector.collectDependencies(DefaultDependencyCollector.java:254)
        ... 26 more
Caused by: org.eclipse.aether.resolution.ArtifactResolutionException: Could not transfer artifact jlibs:jlibs-xml:pom:1.0 from/to kepler (http://download.eclipse.org/releases/kepler): Cannot access http://download.eclipse.org/releases/kepler with type p2 using the available connector factories: BasicRepositoryConnectorFactory
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:444)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifacts(DefaultArtifactResolver.java:246)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolveArtifact(DefaultArtifactResolver.java:223)
        at org.apache.maven.repository.internal.DefaultArtifactDescriptorReader.loadPom(DefaultArtifactDescriptorReader.java:287)
        ... 37 more
Caused by: org.eclipse.aether.transfer.ArtifactTransferException: Could not transfer artifact jlibs:jlibs-xml:pom:1.0 from/to kepler (http://download.eclipse.org/releases/kepler): Cannot access http://download.eclipse.org/releases/kepler with type p2 using the available connector factories: BasicRepositoryConnectorFactory
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:531)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.resolve(DefaultArtifactResolver.java:421)
        ... 40 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access http://download.eclipse.org/releases/kepler with type p2 using the available connector factories: BasicRepositoryConnectorFactory
        at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:174)
        at org.eclipse.aether.internal.impl.DefaultArtifactResolver.performDownloads(DefaultArtifactResolver.java:516)
        ... 41 more
Caused by: org.eclipse.aether.transfer.NoRepositoryConnectorException: Cannot access http://download.eclipse.org/releases/kepler with type p2 using the available layout factories: Maven2RepositoryLayoutFactory
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:111)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnectorFactory.newInstance(BasicRepositoryConnectorFactory.java:180)
        at org.eclipse.aether.internal.impl.DefaultRepositoryConnectorProvider.newRepositoryConnector(DefaultRepositoryConnectorProvider.java:113)
        ... 42 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Cannot access http://download.eclipse.org/releases/kepler with type p2 using the available layout factories: Maven2RepositoryLayoutFactory
        at org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:142)
        at org.eclipse.aether.connector.basic.BasicRepositoryConnector.<init>(BasicRepositoryConnector.java:107)
        ... 44 more
Caused by: org.eclipse.aether.transfer.NoRepositoryLayoutException: Unsupported repository layout p2
        at org.eclipse.aether.internal.impl.Maven2RepositoryLayoutFactory.newInstance(Maven2RepositoryLayoutFactory.java:64)
        at org.eclipse.aether.internal.impl.DefaultRepositoryLayoutProvider.newRepositoryLayout(DefaultRepositoryLayoutProvider.java:111)
        ... 45 more
[ERROR]
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginResolutionException
```

**Comment by ddossot** [comment]
I believe this is a duplicate of https://github.com/mulesoft/raml-for-jax-rs/issues/84

Version `1.3.4-SNAPSHOT` shouldn't have the issue anymore: give it a try.

**Comment by McFoggy** [comment]
probably, i'll give it a try tomorrow now.

**Comment by McFoggy** [comment]
I confirm that it works with version `1.3.4-SNAPSHOT`.
