### ISSUE TITLE
Gradle plugin failing

### ISSUE THREAD

**Issue by lucassimaoo** [mulesoft/raml-for-jax-rs#168]
Hi, I am trying to use the new gradle-plugin released under version 1.3.4 but I am getting this exception when running raml-generate.

org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'org.gradle.api.internal.plugins.DefaultConvention@4bbc21bd' with class 'org.gradle.api.internal.plugins.DefaultConvention' to class 'java.util.List'
	at org.raml.jaxrs.gradle.codegen.CodeGeneratorTask.getGeneratorExtensions(CodeGeneratorTask.groovy:122)
	at org.raml.jaxrs.gradle.codegen.CodeGeneratorTask_Decorated.getGeneratorExtensions(Unknown Source)

This is because in the CodeGeneratorTask its trying to use the Configuration.extensions property which is of type GeneratorExtension and not String. 

I fixed this locally but then another error showed up:

aused by: org.gradle.internal.reflect.ObjectInstantiationException: Could not create an instance of type org.raml.jaxrs.gradle.RamlExtension_Decorated.
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:51)
	at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
	at org.gradle.api.internal.plugins.DefaultConvention.create(DefaultConvention.java:106)
	at org.raml.jaxrs.gradle.RamlPlugin.apply(RamlPlugin.groovy:42)
	at org.raml.jaxrs.gradle.RamlPlugin.apply(RamlPlugin.groovy)
	at org.gradle.api.internal.plugins.ImperativeOnlyPluginApplicator.applyImperative(ImperativeOnlyPluginApplicator.java:35)
	at org.gradle.api.internal.plugins.RuleBasedPluginApplicator.applyImperative(RuleBasedPluginApplicator.java:44)
	at org.gradle.api.internal.plugins.DefaultPluginManager.doApply(DefaultPluginManager.java:144)
	... 61 more
Caused by: java.lang.NoClassDefFoundError: org/raml/jaxrs/codegen/core/Configuration$JaxrsVersion
	at org.raml.jaxrs.gradle.RamlExtension.<init>(RamlExtension.groovy)
	at org.raml.jaxrs.gradle.RamlExtension_Decorated.<init>(Unknown Source)
	at org.gradle.internal.reflect.DirectInstantiator.newInstance(DirectInstantiator.java:49)
	... 68 more
Caused by: java.lang.ClassNotFoundException: org.raml.jaxrs.codegen.core.Configuration$JaxrsVersion
	... 71 more

Looks like the jar for the plugin that maven is building does not contains all the dependencies that it needs.

Any thoughts?

**Comment by alexanderosipov** [comment]
Hello, 
could you please provide your build.gradle file?

**Comment by alexanderosipov** [comment]
Clear, that's incompatibility with gradle v2.8+

**Comment by alexanderosipov** [comment]
Fixed in 1.3.5-SNAPSHOT
