### ISSUE TITLE
Maven plugin doesn't work with java 8 source code

### ISSUE THREAD

**Issue by dmgcodevil** [mulesoft/raml-for-jax-rs#64]
Hi all,

I’ve tried to use raml maven plugin (jaxrs-raml-maven-plugin) to generate raml files but it seems that the plugin doesn’t support java 8.

I performed “mvn compile” and got the following errors:
```
015-04-14 11:13:18,721 ERROR spoon.support.compiler.jdt.JDTTreeBuilder - unconsistent message send at (d:/project/src/main/java/rest/resource/Resource.java:51)
       at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.report(JDTBasedSpoonCompiler.java:506)
       at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.reportProblems(JDTBasedSpoonCompiler.java:521)
       at spoon.support.compiler.jdt.JDTBasedSpoonCompiler.build(JDTBasedSpoonCompiler.java:481)
       at spoon.Launcher.run(Launcher.java:822)
       at spoon.Launcher.run(Launcher.java:910)
       at org.raml.jaxrs.codegen.maven.JaxrsRamlCodegenMojo.execute(JaxrsRamlCodegenMojo.java:135)
       at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:132)
```

WDYT ?

**Comment by dmgcodevil** [comment]
Fixed. I bumped up version of fr.inria.gforge.spoon, please see [PL](https://github.com/mulesoft/raml-for-jax-rs/pull/65)
