### ISSUE TITLE
NullPointerException in AbstractGenerator.addCatchAllFormParametersArgument

### ISSUE THREAD

**Issue by sumveds** [mulesoft/raml-for-jax-rs#97]
Dear Team,

I have written schemas using schema draft 4.0. I am trying to generate JAX-RS interfaces & the resources but, unable to do so. It seems in version 1.3.3 only draft 3.0 is supported.

While generating the JAX-RS classes via maven plugin, I get following error trace:

```
[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3:generate (default) on project api: Error generating Java classes from: /Users/sumvedshami/dev/githome/akosha-api/src/main/resources/api/v1.0/api.raml: Unrecognised URI, can't resolve this: file:/var/folders/cc/1x8jcvhn4c9253b00cgd6mmc0000gn/T/1433220609060-0/address.json: /var/folders/cc/1x8jcvhn4c9253b00cgd6mmc0000gn/T/1433220609060-0/address.json (No such file or directory) -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3:generate (default) on project api: Error generating Java classes from: /Users/sumvedshami/dev/githome/akosha-api/src/main/resources/api/v1.0/api.raml
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java classes from: /Users/sumvedshami/dev/githome/akosha-api/src/main/resources/api/v1.0/api.raml
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:225)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.IllegalArgumentException: Unrecognised URI, can't resolve this: file:/var/folders/cc/1x8jcvhn4c9253b00cgd6mmc0000gn/T/1433220609060-0/address.json
	at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:71)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:47)
	at org.jsonschema2pojo.SchemaStore.create(SchemaStore.java:93)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:59)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:76)
	at org.jsonschema2pojo.rules.PropertyRule.apply(PropertyRule.java:42)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:60)
	at org.jsonschema2pojo.rules.PropertiesRule.apply(PropertiesRule.java:31)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:120)
	at org.jsonschema2pojo.rules.ObjectRule.apply(ObjectRule.java:64)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:85)
	at org.jsonschema2pojo.rules.TypeRule.apply(TypeRule.java:35)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:73)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:66)
	at org.jsonschema2pojo.rules.SchemaRule.apply(SchemaRule.java:30)
	at org.jsonschema2pojo.SchemaMapper.generate(SchemaMapper.java:88)
	at org.raml.jaxrs.codegen.core.Context.generateClassFromJsonSchema(Context.java:413)
	at org.raml.jaxrs.codegen.core.Types.getSchemaClass(Types.java:234)
	at org.raml.jaxrs.codegen.core.Types.getRequestEntityClass(Types.java:123)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addPlainBodyArgument(AbstractGenerator.java:375)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addBodyParameters(AbstractGenerator.java:473)
	at org.raml.jaxrs.codegen.core.Generator.addResourceMethod(Generator.java:159)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:653)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:227)
	at org.raml.jaxrs.codegen.core.Generator.createResourceInterface(Generator.java:111)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.run(AbstractGenerator.java:171)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.run(AbstractGenerator.java:709)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:222)
	... 21 more
Caused by: java.io.FileNotFoundException: /var/folders/cc/1x8jcvhn4c9253b00cgd6mmc0000gn/T/1433220609060-0/address.json (No such file or directory)
	at java.io.FileInputStream.open(Native Method)
	at java.io.FileInputStream.<init>(FileInputStream.java:146)
	at java.io.FileInputStream.<init>(FileInputStream.java:101)
	at com.fasterxml.jackson.core.JsonFactory._optimizedStreamFromURL(JsonFactory.java:1414)
	at com.fasterxml.jackson.core.JsonFactory.createParser(JsonFactory.java:730)
	at com.fasterxml.jackson.databind.ObjectMapper.readTree(ObjectMapper.java:1860)
	at org.jsonschema2pojo.ContentResolver.resolve(ContentResolver.java:65)
	... 49 more
```

Thank you.

Regards,
Sumved Shami

**Comment by ddossot** [comment]
RAML->JAX-RS codegen relies on http://www.jsonschema2pojo.org/ , which currently supports JSON Schema `draft-3` only.

This said, the issue you are facing doesn't seem related to this but to the fact that the `address.json` schema can not be loaded, which looks like you're getting hit by this issue: https://github.com/mulesoft/raml-for-jax-rs/issues/61

@petrochenko-pavel-a Any idea when the next release will be available? Issue #61 is causing lots of grief...

**Comment by sumveds** [comment]
I tried changing the api specification and made it according to the schema draft 3.0

I am able to generate the api documentation via api designer tool. But, unable to generate the jax-rs interfaces/resources. I am getting null pointer exception now.
```
[ERROR] Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3:generate (default) on project api: Error generating Java classes from: /Users/sumvedshami/dev/githome/akosha-api/src/main/resources/api/v1.0/api.raml: NullPointerException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.raml.plugins:raml-jaxrs-maven-plugin:1.3.3:generate (default) on project api: Error generating Java classes from: /Users/sumvedshami/dev/githome/akosha-api/src/main/resources/api/v1.0/api.raml
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:216)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:108)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:76)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:116)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:361)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:155)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:584)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:213)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:157)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.MojoExecutionException: Error generating Java classes from: /Users/sumvedshami/dev/githome/akosha-api/src/main/resources/api/v1.0/api.raml
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:225)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:133)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 19 more
Caused by: java.lang.NullPointerException
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addCatchAllFormParametersArgument(AbstractGenerator.java:309)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addBodyParameters(AbstractGenerator.java:470)
	at org.raml.jaxrs.codegen.core.Generator.addResourceMethod(Generator.java:159)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:653)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:227)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:238)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.addResourceMethods(AbstractGenerator.java:238)
	at org.raml.jaxrs.codegen.core.Generator.createResourceInterface(Generator.java:111)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.run(AbstractGenerator.java:171)
	at org.raml.jaxrs.codegen.core.AbstractGenerator.run(AbstractGenerator.java:709)
	at org.raml.jaxrs.codegen.maven.RamlJaxrsCodegenMojo.execute(RamlJaxrsCodegenMojo.java:222)
	... 21 more
```
The maven plugin in pom.xml file looks like this:
```
<plugin>
  <groupId>org.raml.plugins</groupId>
  <artifactId>raml-jaxrs-maven-plugin</artifactId>
  <version>1.3.3</version>
  <configuration>
    <sourcePaths>
      <sourcePath>${basedir}/src/main/resources/api/v1.0/api.raml</sourcePath>
    </sourcePaths>
    <basePackageName>com.akosha.api.resource</basePackageName>
    <JAX-RSVersion>2.0</JAX-RSVersion>
    <useJsr303Annotations>true</useJsr303Annotations>
    <jsonMapper>jackson2</jsonMapper>
    <removeOldOutput>true</removeOldOutput>
  </configuration>
  <executions>
    <execution>
      <goals>
        <goal>generate</goal>
      </goals>
      <phase>generate-sources</phase>
    </execution>
  </executions>
</plugin>
```

Can anyone please let me know what could be the issue?

**Comment by sumveds** [comment]
APi specification:
```
title: Akosha API
baseUri: http://api.akosha.com/{version}
version: v1.0
protocols: [HTTP, HTTPS]
mediaType: application/json
documentation:
 - title: Home
   content: |
     Welcome to the _Akosha API_ Documentation. The _Akosha API_
     allows you to connect your application to our chat service. You may also benefit from one of our [engineering blog](http://engineering.akosha.com/) to understand that how did we actually scale our application.
schemas:
  - error: | 
      {
        "type": "object",
        "$schema": "http://json-schema.org/draft-03/schema",
        "title": "Error response schema.",
        "description": "A generic error response schema.",
        "name": "error",
        "properties": {
          "status": {
            "type": "integer",
            "title": "status",
            "description": "HTTP status code."
          },
          "code": {
            "type": "string",
            "title": "code",
            "description": "Application level error code."
          },
          "message": {
            "type": "string",
            "title": "message",
            "description": "Error message."
          },
          "info": {
            "type": "string",
            "title": "doc",
            "name": "doc",
            "description": "Error web documentation link."
          },
          "details": {
            "type": "array",
            "title": "Detailed error messages.",
            "description": "Detailed error messages.",
            "name": "details",
            "items": {
              "type": "string"
              },
            "minItems": 1,
            "uniqueItems": true
          }
        }
      }
  - address: | 
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "title": "Address schema.",
        "description": "A generic address schema.",
        "name": "address",
        "properties": {
          "line1": {
            "type": "string",
            "title": "line1",
            "description": "Address line 1"
          },
          "line2": {
            "type": "string",
            "title": "line2",
            "name": "line2",
            "description": "Address line 2"
          },
          "city": {
            "type": "string",
            "title": "city",
            "name": "city",
            "description": "Name of the city"
          },
          "state": {
            "type": "string",
            "title": "state",
            "name": "state",
            "description": "Name of the state"
          },
          "country": {
            "type": "string",
            "title": "country",
            "name": "country",
            "description": "Name of the country"
          },
          "zipcode": {
            "type": "string",
            "title": "zipcode",
            "name": "zipcode",
            "description": "Zipcode"
          }
        }
      }
  - brand_category: | 
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "title": "Brand category.",
        "description": "Brand category schema.",
        "name": "brand_category",
        "properties": {
          "id": {
            "type": "integer",
            "title": "Brand category identifier",
            "description": "Brand category identifier.",
            "name": "category_id"
          },
          "name": {
            "type": "string",
            "title": "Brand category name",
            "description": "Brand category name.",
            "name": "category_name"
          }
        }
      }
  - mobile: | 
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "title": "User",
        "name": "user",
        "description": "User detailed information.",
        "properties": {
          "number": {
            "type": "string",
            "title": "Mobile number",
            "description": "Mobile number.",
            "name": "number"
          },
          "status": {
            "type": "string",
            "enum": [
              "active",
              "inactive",
              "deleted"
            ],
            "title": "Status",
            "description": "Status of the mobile number.",
            "name": "status"
          },
          "otp_authenticated": {
            "type": "boolean",
            "title": "Mobile opt authenticated",
            "description": "Mobile opt authenticated.",
            "name": "otp_authenticated"
          }
        }
      }
  - brand: | 
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "title": "Brand",
        "name": "brand",
        "description": "An explanation about the purpose of this instance described by this schema.",
        "properties": {
          "id": {
            "type": "string",
            "title": "Id",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "id"
          },
          "name": {
            "type": "string",
            "title": "Name",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "name"
          },
          "active": {
            "type": "boolean",
            "title": "Active",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "active"
          },
          "channel": {
            "type": "boolean",
            "title": "Channel",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "channel"
          },
          "address": {
            "$ref": "address"
          },
          "categories": {
            "type": "array",
            "items": {
              "$ref": "brand_category",
              "type": "object"
            }
          },
          "website": {
            "type": "string",
            "title": "Website",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "website"
          },
          "logo": {
            "type": "string",
            "title": "Logo",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "logo"
          },
          "support_email": {
            "type": "string",
            "title": "Support email",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "support_email"
          },
          "twitter_url": {
            "type": "string",
            "title": "Twitter url",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "twitter_url"
          },
          "facebook_url": {
            "type": "string",
            "title": "Facebook url",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "facebook_url"
          },
          "powered_by": {
            "type": "string",
            "title": "Powered by",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "powered_by"
          },
          "verified": {
            "type": "boolean",
            "title": "Verified schema.",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "verified"
          },
          "created_time": {
            "type": "integer",
            "title": "Created timestamp of the brand.",
            "description": "Created timestamp.",
            "name": "created_time"
          },
          "last_updated_time": {
            "type": "integer",
            "title": "Last update timestamp of brand.",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "last_updated_time"
          }
        }
      }
  - brands: | 
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "title": "Brands schema.",
        "description": "An explanation about the purpose of this instance described by this schema.",
        "name": "brands",
        "properties": {
          "brands": {
            "type": "array",
            "title": "Brands schema.",
            "description": "An explanation about the purpose of this instance described by this schema.",
            "name": "brands",
            "items": {
              "$ref": "brand",
              "type": "object"
            },
            "minItems": 1,
            "uniqueItems": true
          }
        }
      }
  - user: | 
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "title": "User",
        "name": "user",
        "description": "User detailed information.",
        "properties": {
          "id": {
            "type": "integer",
            "title": "Id",
            "description": "Unique identifier of the user.",
            "name": "id"
          },
          "name": {
            "type": "string",
            "title": "Name",
            "description": "Name of the user.",
            "name": "name"
          },
          "email": {
            "type": "string",
            "title": "Email",
            "description": "Email of the user.",
            "name": "email"
          },
          "mobile": {
            "$ref": "mobile"
          },
          "address": {
            "$ref": "address"
          },
          "image_url": {
            "type": "string",
            "title": "Image url",
            "description": "Image URL of the user.",
            "name": "image_url"
          },
          "status": {
            "type": "string",
            "enum": [
              "active",
              "inactive",
              "deleted"
            ],
            "title": "Status",
            "description": "Status of the user.",
            "name": "status"
          },
          "created_time": {
            "type": "integer",
            "title": "Created timestamp of the user.",
            "description": "Created timestamp.",
            "name": "created_time"
          },
          "last_updated_time": {
            "type": "integer",
            "title": "Last update timestamp of user.",
            "description": "Last updated timestamp.",
            "name": "last_updated_time"
          }
        }
      }
  - patch: | 
      {
        "$schema": "http://json-schema.org/draft-03/schema",
        "type": "object",
        "title": "Patch",
        "description": "A generic patch schema.",
        "name": "Patch",
        "properties": {
          "op": {
            "type": "string",
            "enum": [
              "add",
              "replace",
              "remove"
            ],
            "description": "Operation to be done on the JSON field provided in path."
          },
          "path": {
            "type": "string",
            "title": "Path",
            "name": "path",
            "description": "JSON field to be added/updated/removed."
          },
          "value": {
            "type": "object",
            "title": "Value",
            "name": "value",
            "description": "Value to be added/replaced."
          }
        }
      }
/brands:
  description: Brands resource.
  post:
    description: Create a brand resource.
    headers:
      Content-Type:
        required: true
      Accept:
        required: true
    body:
      application/json: 
        schema: brand
        example: | 
          {
            "name": "WhereAbout1",
            "active": true,
            "channel": false,
            "address": {
              "line1": "WhereAbout (India) Ltd,\r\nAndheri(E), Mumbai-400093.\r\nTel: 91-22-6741 0000, Fax:91-22-6742 0008"
            },
            "website": "https://www.goair.in/",
            "logo": "akosha_whereabout.png",
            "support_email": "support@whereabout.com",
            "twitter_url": "https://twitter.com/WhereAbout",
            "facebook_url": "https://www.facebook.com/WhereAbout",
            "verified": false
          }
    responses:
      201:
        headers:
          Location:
            required: true
        description: Created
      400:
        description: Bad request
        body:
          application/json:
            schema: error
            example:
  get:
    description: Get all brands added/updated/deleted after provided timestamp.
    headers:
      Accept: 
        required: true
    queryParameters:
      timestamp: 
        required: true
        type: number
        minimum: 946684800000
        example: 1432980993000
    responses:
      200:
        description: OK
        body:
          application/json:
            schema: brands
            example: | 
              [
                {
                  "id": "6156",
                  "name": "Madhur123",
                  "active": true,
                  "channel": false,
                  "address": {
                    "line1": ""
                  },
                  "categories": [
                    {
                      "id": 11,
                      "name": "Real Estate/Construction"
                    }
                  ],
                  "website": "",
                  "support_email": "",
                  "twitter_url": "",
                  "facebook_url": "",
                  "verified": false,
                  "created_time": 1429556208000,
                  "last_updated_time": 1429556208000
                },
                {
                  "id": "6154",
                  "name": "Hitesh-Android",
                  "active": true,
                  "channel": false,
                  "address": {
                    "line1": ""
                  },
                  "categories": [
                    {
                      "id": 13,
                      "name": "Holidays/Transport/Travel"
                    }
                  ],
                  "website": "",
                  "support_email": "",
                  "twitter_url": "",
                  "facebook_url": "",
                  "verified": false,
                  "created_time": 1429555935000,
                  "last_updated_time": 1429556017000
                }
              ]
  /{brandId}: 
    get:
      description: Get brand resource by id.
      headers:
        Accept:
          required: true
      responses:
        200:
          body:
            application/json:
              schema: brand
              example: |
                {
                  "id": "1",
                  "name": "Go Air",
                  "active": true,
                  "channel": false,
                  "address": {
                    "line1": "Go Airlines (India) Ltd.\r\nPaper Box House,\r\nOff Mahakali Caves Road,\r\nAndheri(E), Mumbai-400093.\r\nTel: 91-22-6741 0000, Fax:91-22-6742 0008"
                  },
                  "categories": [
                    {
                      "id": 1,
                      "name": "Airlines"
                    }
                  ],
                  "website": "https://www.goair.in/",
                  "logo": "akosha_go_air.png",
                  "support_email": "Refunds@goair.in",
                  "twitter_url": "https://twitter.com/goairlinesindia",
                  "facebook_url": "https://www.facebook.com/GoAir",
                  "verified": false,
                  "created_time": 1415782236000,
                  "last_updated_time": 1419684026000
                }
        404:
          description: Not found
          body:
            application/json:
              schema: error
    put:
      description: Replace brand resource.
      headers:
        Content-Type:
          required: true
      body:
        application/json:
          schema: brand
          example: | 
            {
              "name": "Go Air",
              "active": true,
              "channel": false,
              "address": {
                "line1": "Go Airlines (India) Ltd.\r\nPaper Box House,\r\nOff Mahakali Caves Road,\r\nAndheri(E), Mumbai-400093.\r\nTel: 91-22-6741 0000, Fax:91-22-6742 0008 "
              },
              "categories": [
                {
                  "id": 1,
                  "name": "Airlines"
                }
              ],
              "website": "https://www.goair.in/",
              "logo": "akosha_go_air.png",
              "support_email": "Refunds@goair.in",
              "twitter_url": "https://twitter.com/goairlinesindia",
              "facebook_url": "https://www.facebook.com/GoAir"
            }
      responses:
        204:
          description: No content
    delete:
      description: Delete brand resource.
      responses:
        204:
          description: No content
        404:
          description: Not found
          body:
            application/json:
              schema: error
/users:
  displayName: Users resource
  post:
    description: Create a user resource.
    headers:
      Accept: 
        required: true
        example: application/json
    body:
      application/json: 
        schema: user
        example:
    responses:
      201:
        description: Created
  /{userId}:
    description: Specific user resource endpoints.
    get:
      description: Get the user resource of the provided user id.
      headers:
        Accept:
          required: true
      responses:
        200:
          body:
            application/json:
              schema: user
              example:
        404: 
          description: Not found
          body:
              application/json:
                schema: error
    put:
      description: Replace user resource.
      headers:
        Content-Type:
          required: true
          example: application/json
      body:
        application/json:
          schema: user
          example:
      responses:
        204:
          description: No content
    /brands:
      get:
        description: Get the user favourite brands resource.
        headers:
          Accept:
            required: true
            example: application/json
        responses:
          200:
            description: OK
            body:
              application/json:
                schema: brands
                example:
          404:
            description: Not found
            body:
              application/json:
                schema: error
      patch:
        description: Update the user favourite companies resource.
        headers:
          Accept:
            required: true
            example: application/json
          Content-Type:
            required: true
            example: application/json
        body:
          application/json:
            schema: patch
        responses:
          200:
            description: OK
            body:
              application/json:
                schema: brands
                example:
    /photos:
      description: User profile photo resource.
      post:
        description: Upload profile photo resource of the user.
        headers:
          Content-Type: 
            required: true
        body:
          multipart/form-data:
        responses:
          202:
            description: Accepted
            headers:
              Link:
                required: true
    /messages:
      description: User messages resource.
      post:
        description: Send file to the agent.
        queryParameters:
          to: 
            description: Receiver id.
            example: 123456789
            required: true
            type: number
        headers:
          Content-Type: 
            required: true
        body:
          multipart/form-data:
        responses:
          202:
            description: Accepted
            headers:
              Link:
                required: true
```

**Comment by ddossot** [comment]
This looks like a bug, an NPE should never be raised like this.

Can you rename this issue from `Json schema draft 4 unsupported` to `NullPointerException in AbstractGenerator.addCatchAllFormParametersArgument` so it makes it clear what problem you are facing?

**Comment by KonstantinSviridov** [comment]
Hi, @sumveds 

Thanks for reporting the problem.
I've pushed fix to 1.3.4-SNAPSHOT.

Regards, Konstantin.

**Comment by KonstantinSviridov** [comment]
The problem was due to empty set of form parameters in your `multipart/form-data` bodies.

**Comment by sumveds** [comment]
Hi @KonstantinSviridov - Where can I find 1.3.4-SNAPSHOT version so that I can test the changes? Thanks a ton for your quick fix.

**Comment by sumveds** [comment]
Hey @KonstantinSviridov - Sorry about the above message. I am able to generate the classes now. Many many thanks for the quick fix. When is 1.3.4 version is supposed to go in the release pool?
